/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ConfirmBookingRouteImport } from './routes/confirm-booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CallSlugRouteImport } from './routes/call.$slug'
import { Route as AppAuthRouteImport } from './routes/app/auth'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppAuthenticatedTicketsRouteImport } from './routes/app/_authenticated/tickets'
import { Route as AppAuthenticatedSetPasswordRouteImport } from './routes/app/_authenticated/set-password'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/app/_authenticated/profile'
import { Route as AppAuthenticatedCommissionsRouteImport } from './routes/app/_authenticated/commissions'
import { Route as ApiPublicConfirmBookingRouteImport } from './routes/api/public/confirm-booking'
import { Route as AppAuthenticatedAdminRouteRouteImport } from './routes/app/_authenticated/admin/route'
import { Route as AppAuthenticatedTrainingIndexRouteImport } from './routes/app/_authenticated/training.index'
import { Route as AppAuthenticatedDmSetterIndexRouteImport } from './routes/app/_authenticated/dm-setter/index'
import { Route as AppAuthenticatedDmManagerIndexRouteImport } from './routes/app/_authenticated/dm-manager/index'
import { Route as AppAuthenticatedCloserIndexRouteImport } from './routes/app/_authenticated/closer/index'
import { Route as AppAuthenticatedAdminIndexRouteImport } from './routes/app/_authenticated/admin/index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppAuthenticatedTrainingModuleIdRouteImport } from './routes/app/_authenticated/training.$moduleId'
import { Route as AppAuthenticatedDmSetterLogsRouteImport } from './routes/app/_authenticated/dm-setter/logs'
import { Route as AppAuthenticatedDmSetterInboxRouteImport } from './routes/app/_authenticated/dm-setter/inbox'
import { Route as AppAuthenticatedDmSetterCalendarRouteImport } from './routes/app/_authenticated/dm-setter/calendar'
import { Route as AppAuthenticatedDmManagerModulesRouteImport } from './routes/app/_authenticated/dm-manager/modules'
import { Route as AppAuthenticatedDmManagerCalendarRouteImport } from './routes/app/_authenticated/dm-manager/calendar'
import { Route as AppAuthenticatedCloserCommissionsRouteImport } from './routes/app/_authenticated/closer/commissions'
import { Route as AppAuthenticatedCloserCalendarRouteImport } from './routes/app/_authenticated/closer/calendar'
import { Route as AppAuthenticatedAdminTicketsRouteImport } from './routes/app/_authenticated/admin/tickets'
import { Route as AppAuthenticatedAdminSettingsRouteImport } from './routes/app/_authenticated/admin/settings'
import { Route as AppAuthenticatedAdminQuizzesRouteImport } from './routes/app/_authenticated/admin/quizzes'
import { Route as AppAuthenticatedAdminPifPaymentsRouteImport } from './routes/app/_authenticated/admin/pif-payments'
import { Route as AppAuthenticatedAdminModulesRouteImport } from './routes/app/_authenticated/admin/modules'
import { Route as AppAuthenticatedAdminManagerCalendarsRouteImport } from './routes/app/_authenticated/admin/manager-calendars'
import { Route as AppAuthenticatedAdminDmSettersRouteImport } from './routes/app/_authenticated/admin/dm-setters'
import { Route as AppAuthenticatedAdminClosersRouteImport } from './routes/app/_authenticated/admin/closers'
import { Route as AppAuthenticatedAdminBookingsRouteImport } from './routes/app/_authenticated/admin/bookings'
import { Route as AppAuthenticatedAdminB2cCommissionsRouteImport } from './routes/app/_authenticated/admin/b2c-commissions'
import { Route as AppAuthenticatedAdminApplicationsRouteImport } from './routes/app/_authenticated/admin/applications'
import { Route as AppAuthenticatedAdminAdminsRouteImport } from './routes/app/_authenticated/admin/admins'
import { Route as AppAuthenticatedAdminAccountDeletionsRouteImport } from './routes/app/_authenticated/admin/account-deletions'
import { Route as ApiPublicWebhooksSmartleadRouteImport } from './routes/api/public/webhooks/smartlead'
import { Route as ApiPublicHooksSyncPifPaymentsRouteImport } from './routes/api/public/hooks/sync-pif-payments'
import { Route as ApiPublicHooksSmartleadSyncRouteImport } from './routes/api/public/hooks/smartlead-sync'
import { Route as ApiPublicHooksSendCallRemindersRouteImport } from './routes/api/public/hooks/send-call-reminders'
import { Route as ApiPublicHooksPurgeDmScreenshotsRouteImport } from './routes/api/public/hooks/purge-dm-screenshots'
import { Route as ApiPublicHooksMarkUnbookedRouteImport } from './routes/api/public/hooks/mark-unbooked'
import { Route as ApiPublicHooksGhlBookingRouteImport } from './routes/api/public/hooks/ghl-booking'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmBookingRoute = ConfirmBookingRouteImport.update({
  id: '/confirm-booking',
  path: '/confirm-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CallSlugRoute = CallSlugRouteImport.update({
  id: '/call/$slug',
  path: '/call/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedTicketsRoute = AppAuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedSetPasswordRoute =
  AppAuthenticatedSetPasswordRouteImport.update({
    id: '/set-password',
    path: '/set-password',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedCommissionsRoute =
  AppAuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const ApiPublicConfirmBookingRoute = ApiPublicConfirmBookingRouteImport.update({
  id: '/api/public/confirm-booking',
  path: '/api/public/confirm-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedAdminRouteRoute =
  AppAuthenticatedAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedTrainingIndexRoute =
  AppAuthenticatedTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmSetterIndexRoute =
  AppAuthenticatedDmSetterIndexRouteImport.update({
    id: '/dm-setter/',
    path: '/dm-setter/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmManagerIndexRoute =
  AppAuthenticatedDmManagerIndexRouteImport.update({
    id: '/dm-manager/',
    path: '/dm-manager/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCloserIndexRoute =
  AppAuthenticatedCloserIndexRouteImport.update({
    id: '/closer/',
    path: '/closer/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminIndexRoute =
  AppAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAuthenticatedTrainingModuleIdRoute =
  AppAuthenticatedTrainingModuleIdRouteImport.update({
    id: '/training/$moduleId',
    path: '/training/$moduleId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmSetterLogsRoute =
  AppAuthenticatedDmSetterLogsRouteImport.update({
    id: '/dm-setter/logs',
    path: '/dm-setter/logs',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmSetterInboxRoute =
  AppAuthenticatedDmSetterInboxRouteImport.update({
    id: '/dm-setter/inbox',
    path: '/dm-setter/inbox',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmSetterCalendarRoute =
  AppAuthenticatedDmSetterCalendarRouteImport.update({
    id: '/dm-setter/calendar',
    path: '/dm-setter/calendar',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmManagerModulesRoute =
  AppAuthenticatedDmManagerModulesRouteImport.update({
    id: '/dm-manager/modules',
    path: '/dm-manager/modules',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDmManagerCalendarRoute =
  AppAuthenticatedDmManagerCalendarRouteImport.update({
    id: '/dm-manager/calendar',
    path: '/dm-manager/calendar',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCloserCommissionsRoute =
  AppAuthenticatedCloserCommissionsRouteImport.update({
    id: '/closer/commissions',
    path: '/closer/commissions',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCloserCalendarRoute =
  AppAuthenticatedCloserCalendarRouteImport.update({
    id: '/closer/calendar',
    path: '/closer/calendar',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminTicketsRoute =
  AppAuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminSettingsRoute =
  AppAuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminQuizzesRoute =
  AppAuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminPifPaymentsRoute =
  AppAuthenticatedAdminPifPaymentsRouteImport.update({
    id: '/pif-payments',
    path: '/pif-payments',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminModulesRoute =
  AppAuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminManagerCalendarsRoute =
  AppAuthenticatedAdminManagerCalendarsRouteImport.update({
    id: '/manager-calendars',
    path: '/manager-calendars',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminDmSettersRoute =
  AppAuthenticatedAdminDmSettersRouteImport.update({
    id: '/dm-setters',
    path: '/dm-setters',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminClosersRoute =
  AppAuthenticatedAdminClosersRouteImport.update({
    id: '/closers',
    path: '/closers',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminBookingsRoute =
  AppAuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminB2cCommissionsRoute =
  AppAuthenticatedAdminB2cCommissionsRouteImport.update({
    id: '/b2c-commissions',
    path: '/b2c-commissions',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminApplicationsRoute =
  AppAuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminAdminsRoute =
  AppAuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const AppAuthenticatedAdminAccountDeletionsRoute =
  AppAuthenticatedAdminAccountDeletionsRouteImport.update({
    id: '/account-deletions',
    path: '/account-deletions',
    getParentRoute: () => AppAuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksSmartleadRoute =
  ApiPublicWebhooksSmartleadRouteImport.update({
    id: '/api/public/webhooks/smartlead',
    path: '/api/public/webhooks/smartlead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncPifPaymentsRoute =
  ApiPublicHooksSyncPifPaymentsRouteImport.update({
    id: '/api/public/hooks/sync-pif-payments',
    path: '/api/public/hooks/sync-pif-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSmartleadSyncRoute =
  ApiPublicHooksSmartleadSyncRouteImport.update({
    id: '/api/public/hooks/smartlead-sync',
    path: '/api/public/hooks/smartlead-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendCallRemindersRoute =
  ApiPublicHooksSendCallRemindersRouteImport.update({
    id: '/api/public/hooks/send-call-reminders',
    path: '/api/public/hooks/send-call-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeDmScreenshotsRoute =
  ApiPublicHooksPurgeDmScreenshotsRouteImport.update({
    id: '/api/public/hooks/purge-dm-screenshots',
    path: '/api/public/hooks/purge-dm-screenshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarkUnbookedRoute =
  ApiPublicHooksMarkUnbookedRouteImport.update({
    id: '/api/public/hooks/mark-unbooked',
    path: '/api/public/hooks/mark-unbooked',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGhlBookingRoute =
  ApiPublicHooksGhlBookingRouteImport.update({
    id: '/api/public/hooks/ghl-booking',
    path: '/api/public/hooks/ghl-booking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/confirm-booking': typeof ConfirmBookingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/auth': typeof AppAuthRoute
  '/call/$slug': typeof CallSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/admin': typeof AppAuthenticatedAdminRouteRouteWithChildren
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/app/commissions': typeof AppAuthenticatedCommissionsRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/set-password': typeof AppAuthenticatedSetPasswordRoute
  '/app/tickets': typeof AppAuthenticatedTicketsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/ghl-booking': typeof ApiPublicHooksGhlBookingRoute
  '/api/public/hooks/mark-unbooked': typeof ApiPublicHooksMarkUnbookedRoute
  '/api/public/hooks/purge-dm-screenshots': typeof ApiPublicHooksPurgeDmScreenshotsRoute
  '/api/public/hooks/send-call-reminders': typeof ApiPublicHooksSendCallRemindersRoute
  '/api/public/hooks/smartlead-sync': typeof ApiPublicHooksSmartleadSyncRoute
  '/api/public/hooks/sync-pif-payments': typeof ApiPublicHooksSyncPifPaymentsRoute
  '/api/public/webhooks/smartlead': typeof ApiPublicWebhooksSmartleadRoute
  '/app/admin/account-deletions': typeof AppAuthenticatedAdminAccountDeletionsRoute
  '/app/admin/admins': typeof AppAuthenticatedAdminAdminsRoute
  '/app/admin/applications': typeof AppAuthenticatedAdminApplicationsRoute
  '/app/admin/b2c-commissions': typeof AppAuthenticatedAdminB2cCommissionsRoute
  '/app/admin/bookings': typeof AppAuthenticatedAdminBookingsRoute
  '/app/admin/closers': typeof AppAuthenticatedAdminClosersRoute
  '/app/admin/dm-setters': typeof AppAuthenticatedAdminDmSettersRoute
  '/app/admin/manager-calendars': typeof AppAuthenticatedAdminManagerCalendarsRoute
  '/app/admin/modules': typeof AppAuthenticatedAdminModulesRoute
  '/app/admin/pif-payments': typeof AppAuthenticatedAdminPifPaymentsRoute
  '/app/admin/quizzes': typeof AppAuthenticatedAdminQuizzesRoute
  '/app/admin/settings': typeof AppAuthenticatedAdminSettingsRoute
  '/app/admin/tickets': typeof AppAuthenticatedAdminTicketsRoute
  '/app/closer/calendar': typeof AppAuthenticatedCloserCalendarRoute
  '/app/closer/commissions': typeof AppAuthenticatedCloserCommissionsRoute
  '/app/dm-manager/calendar': typeof AppAuthenticatedDmManagerCalendarRoute
  '/app/dm-manager/modules': typeof AppAuthenticatedDmManagerModulesRoute
  '/app/dm-setter/calendar': typeof AppAuthenticatedDmSetterCalendarRoute
  '/app/dm-setter/inbox': typeof AppAuthenticatedDmSetterInboxRoute
  '/app/dm-setter/logs': typeof AppAuthenticatedDmSetterLogsRoute
  '/app/training/$moduleId': typeof AppAuthenticatedTrainingModuleIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/admin/': typeof AppAuthenticatedAdminIndexRoute
  '/app/closer/': typeof AppAuthenticatedCloserIndexRoute
  '/app/dm-manager/': typeof AppAuthenticatedDmManagerIndexRoute
  '/app/dm-setter/': typeof AppAuthenticatedDmSetterIndexRoute
  '/app/training/': typeof AppAuthenticatedTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/confirm-booking': typeof ConfirmBookingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/auth': typeof AppAuthRoute
  '/call/$slug': typeof CallSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/app/commissions': typeof AppAuthenticatedCommissionsRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/set-password': typeof AppAuthenticatedSetPasswordRoute
  '/app/tickets': typeof AppAuthenticatedTicketsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/ghl-booking': typeof ApiPublicHooksGhlBookingRoute
  '/api/public/hooks/mark-unbooked': typeof ApiPublicHooksMarkUnbookedRoute
  '/api/public/hooks/purge-dm-screenshots': typeof ApiPublicHooksPurgeDmScreenshotsRoute
  '/api/public/hooks/send-call-reminders': typeof ApiPublicHooksSendCallRemindersRoute
  '/api/public/hooks/smartlead-sync': typeof ApiPublicHooksSmartleadSyncRoute
  '/api/public/hooks/sync-pif-payments': typeof ApiPublicHooksSyncPifPaymentsRoute
  '/api/public/webhooks/smartlead': typeof ApiPublicWebhooksSmartleadRoute
  '/app/admin/account-deletions': typeof AppAuthenticatedAdminAccountDeletionsRoute
  '/app/admin/admins': typeof AppAuthenticatedAdminAdminsRoute
  '/app/admin/applications': typeof AppAuthenticatedAdminApplicationsRoute
  '/app/admin/b2c-commissions': typeof AppAuthenticatedAdminB2cCommissionsRoute
  '/app/admin/bookings': typeof AppAuthenticatedAdminBookingsRoute
  '/app/admin/closers': typeof AppAuthenticatedAdminClosersRoute
  '/app/admin/dm-setters': typeof AppAuthenticatedAdminDmSettersRoute
  '/app/admin/manager-calendars': typeof AppAuthenticatedAdminManagerCalendarsRoute
  '/app/admin/modules': typeof AppAuthenticatedAdminModulesRoute
  '/app/admin/pif-payments': typeof AppAuthenticatedAdminPifPaymentsRoute
  '/app/admin/quizzes': typeof AppAuthenticatedAdminQuizzesRoute
  '/app/admin/settings': typeof AppAuthenticatedAdminSettingsRoute
  '/app/admin/tickets': typeof AppAuthenticatedAdminTicketsRoute
  '/app/closer/calendar': typeof AppAuthenticatedCloserCalendarRoute
  '/app/closer/commissions': typeof AppAuthenticatedCloserCommissionsRoute
  '/app/dm-manager/calendar': typeof AppAuthenticatedDmManagerCalendarRoute
  '/app/dm-manager/modules': typeof AppAuthenticatedDmManagerModulesRoute
  '/app/dm-setter/calendar': typeof AppAuthenticatedDmSetterCalendarRoute
  '/app/dm-setter/inbox': typeof AppAuthenticatedDmSetterInboxRoute
  '/app/dm-setter/logs': typeof AppAuthenticatedDmSetterLogsRoute
  '/app/training/$moduleId': typeof AppAuthenticatedTrainingModuleIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/admin': typeof AppAuthenticatedAdminIndexRoute
  '/app/closer': typeof AppAuthenticatedCloserIndexRoute
  '/app/dm-manager': typeof AppAuthenticatedDmManagerIndexRoute
  '/app/dm-setter': typeof AppAuthenticatedDmSetterIndexRoute
  '/app/training': typeof AppAuthenticatedTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/confirm-booking': typeof ConfirmBookingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/auth': typeof AppAuthRoute
  '/call/$slug': typeof CallSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/_authenticated/admin': typeof AppAuthenticatedAdminRouteRouteWithChildren
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/app/_authenticated/commissions': typeof AppAuthenticatedCommissionsRoute
  '/app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/app/_authenticated/set-password': typeof AppAuthenticatedSetPasswordRoute
  '/app/_authenticated/tickets': typeof AppAuthenticatedTicketsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/ghl-booking': typeof ApiPublicHooksGhlBookingRoute
  '/api/public/hooks/mark-unbooked': typeof ApiPublicHooksMarkUnbookedRoute
  '/api/public/hooks/purge-dm-screenshots': typeof ApiPublicHooksPurgeDmScreenshotsRoute
  '/api/public/hooks/send-call-reminders': typeof ApiPublicHooksSendCallRemindersRoute
  '/api/public/hooks/smartlead-sync': typeof ApiPublicHooksSmartleadSyncRoute
  '/api/public/hooks/sync-pif-payments': typeof ApiPublicHooksSyncPifPaymentsRoute
  '/api/public/webhooks/smartlead': typeof ApiPublicWebhooksSmartleadRoute
  '/app/_authenticated/admin/account-deletions': typeof AppAuthenticatedAdminAccountDeletionsRoute
  '/app/_authenticated/admin/admins': typeof AppAuthenticatedAdminAdminsRoute
  '/app/_authenticated/admin/applications': typeof AppAuthenticatedAdminApplicationsRoute
  '/app/_authenticated/admin/b2c-commissions': typeof AppAuthenticatedAdminB2cCommissionsRoute
  '/app/_authenticated/admin/bookings': typeof AppAuthenticatedAdminBookingsRoute
  '/app/_authenticated/admin/closers': typeof AppAuthenticatedAdminClosersRoute
  '/app/_authenticated/admin/dm-setters': typeof AppAuthenticatedAdminDmSettersRoute
  '/app/_authenticated/admin/manager-calendars': typeof AppAuthenticatedAdminManagerCalendarsRoute
  '/app/_authenticated/admin/modules': typeof AppAuthenticatedAdminModulesRoute
  '/app/_authenticated/admin/pif-payments': typeof AppAuthenticatedAdminPifPaymentsRoute
  '/app/_authenticated/admin/quizzes': typeof AppAuthenticatedAdminQuizzesRoute
  '/app/_authenticated/admin/settings': typeof AppAuthenticatedAdminSettingsRoute
  '/app/_authenticated/admin/tickets': typeof AppAuthenticatedAdminTicketsRoute
  '/app/_authenticated/closer/calendar': typeof AppAuthenticatedCloserCalendarRoute
  '/app/_authenticated/closer/commissions': typeof AppAuthenticatedCloserCommissionsRoute
  '/app/_authenticated/dm-manager/calendar': typeof AppAuthenticatedDmManagerCalendarRoute
  '/app/_authenticated/dm-manager/modules': typeof AppAuthenticatedDmManagerModulesRoute
  '/app/_authenticated/dm-setter/calendar': typeof AppAuthenticatedDmSetterCalendarRoute
  '/app/_authenticated/dm-setter/inbox': typeof AppAuthenticatedDmSetterInboxRoute
  '/app/_authenticated/dm-setter/logs': typeof AppAuthenticatedDmSetterLogsRoute
  '/app/_authenticated/training/$moduleId': typeof AppAuthenticatedTrainingModuleIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/_authenticated/admin/': typeof AppAuthenticatedAdminIndexRoute
  '/app/_authenticated/closer/': typeof AppAuthenticatedCloserIndexRoute
  '/app/_authenticated/dm-manager/': typeof AppAuthenticatedDmManagerIndexRoute
  '/app/_authenticated/dm-setter/': typeof AppAuthenticatedDmSetterIndexRoute
  '/app/_authenticated/training/': typeof AppAuthenticatedTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/apply'
    | '/auth'
    | '/confirm-booking'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/app/auth'
    | '/call/$slug'
    | '/email/unsubscribe'
    | '/app/admin'
    | '/api/public/confirm-booking'
    | '/app/commissions'
    | '/app/profile'
    | '/app/set-password'
    | '/app/tickets'
    | '/lovable/email/suppression'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/ghl-booking'
    | '/api/public/hooks/mark-unbooked'
    | '/api/public/hooks/purge-dm-screenshots'
    | '/api/public/hooks/send-call-reminders'
    | '/api/public/hooks/smartlead-sync'
    | '/api/public/hooks/sync-pif-payments'
    | '/api/public/webhooks/smartlead'
    | '/app/admin/account-deletions'
    | '/app/admin/admins'
    | '/app/admin/applications'
    | '/app/admin/b2c-commissions'
    | '/app/admin/bookings'
    | '/app/admin/closers'
    | '/app/admin/dm-setters'
    | '/app/admin/manager-calendars'
    | '/app/admin/modules'
    | '/app/admin/pif-payments'
    | '/app/admin/quizzes'
    | '/app/admin/settings'
    | '/app/admin/tickets'
    | '/app/closer/calendar'
    | '/app/closer/commissions'
    | '/app/dm-manager/calendar'
    | '/app/dm-manager/modules'
    | '/app/dm-setter/calendar'
    | '/app/dm-setter/inbox'
    | '/app/dm-setter/logs'
    | '/app/training/$moduleId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/admin/'
    | '/app/closer/'
    | '/app/dm-manager/'
    | '/app/dm-setter/'
    | '/app/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/apply'
    | '/auth'
    | '/confirm-booking'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/app/auth'
    | '/call/$slug'
    | '/email/unsubscribe'
    | '/api/public/confirm-booking'
    | '/app/commissions'
    | '/app/profile'
    | '/app/set-password'
    | '/app/tickets'
    | '/lovable/email/suppression'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/ghl-booking'
    | '/api/public/hooks/mark-unbooked'
    | '/api/public/hooks/purge-dm-screenshots'
    | '/api/public/hooks/send-call-reminders'
    | '/api/public/hooks/smartlead-sync'
    | '/api/public/hooks/sync-pif-payments'
    | '/api/public/webhooks/smartlead'
    | '/app/admin/account-deletions'
    | '/app/admin/admins'
    | '/app/admin/applications'
    | '/app/admin/b2c-commissions'
    | '/app/admin/bookings'
    | '/app/admin/closers'
    | '/app/admin/dm-setters'
    | '/app/admin/manager-calendars'
    | '/app/admin/modules'
    | '/app/admin/pif-payments'
    | '/app/admin/quizzes'
    | '/app/admin/settings'
    | '/app/admin/tickets'
    | '/app/closer/calendar'
    | '/app/closer/commissions'
    | '/app/dm-manager/calendar'
    | '/app/dm-manager/modules'
    | '/app/dm-setter/calendar'
    | '/app/dm-setter/inbox'
    | '/app/dm-setter/logs'
    | '/app/training/$moduleId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/admin'
    | '/app/closer'
    | '/app/dm-manager'
    | '/app/dm-setter'
    | '/app/training'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/apply'
    | '/auth'
    | '/confirm-booking'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/app/_authenticated'
    | '/app/auth'
    | '/call/$slug'
    | '/email/unsubscribe'
    | '/app/_authenticated/admin'
    | '/api/public/confirm-booking'
    | '/app/_authenticated/commissions'
    | '/app/_authenticated/profile'
    | '/app/_authenticated/set-password'
    | '/app/_authenticated/tickets'
    | '/lovable/email/suppression'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/ghl-booking'
    | '/api/public/hooks/mark-unbooked'
    | '/api/public/hooks/purge-dm-screenshots'
    | '/api/public/hooks/send-call-reminders'
    | '/api/public/hooks/smartlead-sync'
    | '/api/public/hooks/sync-pif-payments'
    | '/api/public/webhooks/smartlead'
    | '/app/_authenticated/admin/account-deletions'
    | '/app/_authenticated/admin/admins'
    | '/app/_authenticated/admin/applications'
    | '/app/_authenticated/admin/b2c-commissions'
    | '/app/_authenticated/admin/bookings'
    | '/app/_authenticated/admin/closers'
    | '/app/_authenticated/admin/dm-setters'
    | '/app/_authenticated/admin/manager-calendars'
    | '/app/_authenticated/admin/modules'
    | '/app/_authenticated/admin/pif-payments'
    | '/app/_authenticated/admin/quizzes'
    | '/app/_authenticated/admin/settings'
    | '/app/_authenticated/admin/tickets'
    | '/app/_authenticated/closer/calendar'
    | '/app/_authenticated/closer/commissions'
    | '/app/_authenticated/dm-manager/calendar'
    | '/app/_authenticated/dm-manager/modules'
    | '/app/_authenticated/dm-setter/calendar'
    | '/app/_authenticated/dm-setter/inbox'
    | '/app/_authenticated/dm-setter/logs'
    | '/app/_authenticated/training/$moduleId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/_authenticated/admin/'
    | '/app/_authenticated/closer/'
    | '/app/_authenticated/dm-manager/'
    | '/app/_authenticated/dm-setter/'
    | '/app/_authenticated/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  ConfirmBookingRoute: typeof ConfirmBookingRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CallSlugRoute: typeof CallSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicConfirmBookingRoute: typeof ApiPublicConfirmBookingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicHooksGhlBookingRoute: typeof ApiPublicHooksGhlBookingRoute
  ApiPublicHooksMarkUnbookedRoute: typeof ApiPublicHooksMarkUnbookedRoute
  ApiPublicHooksPurgeDmScreenshotsRoute: typeof ApiPublicHooksPurgeDmScreenshotsRoute
  ApiPublicHooksSendCallRemindersRoute: typeof ApiPublicHooksSendCallRemindersRoute
  ApiPublicHooksSmartleadSyncRoute: typeof ApiPublicHooksSmartleadSyncRoute
  ApiPublicHooksSyncPifPaymentsRoute: typeof ApiPublicHooksSyncPifPaymentsRoute
  ApiPublicWebhooksSmartleadRoute: typeof ApiPublicWebhooksSmartleadRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-booking': {
      id: '/confirm-booking'
      path: '/confirm-booking'
      fullPath: '/confirm-booking'
      preLoaderRoute: typeof ConfirmBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$slug': {
      id: '/call/$slug'
      path: '/call/$slug'
      fullPath: '/call/$slug'
      preLoaderRoute: typeof CallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/tickets': {
      id: '/app/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppAuthenticatedTicketsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/set-password': {
      id: '/app/_authenticated/set-password'
      path: '/set-password'
      fullPath: '/app/set-password'
      preLoaderRoute: typeof AppAuthenticatedSetPasswordRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/profile': {
      id: '/app/_authenticated/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/commissions': {
      id: '/app/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppAuthenticatedCommissionsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/api/public/confirm-booking': {
      id: '/api/public/confirm-booking'
      path: '/api/public/confirm-booking'
      fullPath: '/api/public/confirm-booking'
      preLoaderRoute: typeof ApiPublicConfirmBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/admin': {
      id: '/app/_authenticated/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAuthenticatedAdminRouteRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/training/': {
      id: '/app/_authenticated/training/'
      path: '/training'
      fullPath: '/app/training/'
      preLoaderRoute: typeof AppAuthenticatedTrainingIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-setter/': {
      id: '/app/_authenticated/dm-setter/'
      path: '/dm-setter'
      fullPath: '/app/dm-setter/'
      preLoaderRoute: typeof AppAuthenticatedDmSetterIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-manager/': {
      id: '/app/_authenticated/dm-manager/'
      path: '/dm-manager'
      fullPath: '/app/dm-manager/'
      preLoaderRoute: typeof AppAuthenticatedDmManagerIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/closer/': {
      id: '/app/_authenticated/closer/'
      path: '/closer'
      fullPath: '/app/closer/'
      preLoaderRoute: typeof AppAuthenticatedCloserIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/': {
      id: '/app/_authenticated/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAuthenticatedAdminIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/training/$moduleId': {
      id: '/app/_authenticated/training/$moduleId'
      path: '/training/$moduleId'
      fullPath: '/app/training/$moduleId'
      preLoaderRoute: typeof AppAuthenticatedTrainingModuleIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-setter/logs': {
      id: '/app/_authenticated/dm-setter/logs'
      path: '/dm-setter/logs'
      fullPath: '/app/dm-setter/logs'
      preLoaderRoute: typeof AppAuthenticatedDmSetterLogsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-setter/inbox': {
      id: '/app/_authenticated/dm-setter/inbox'
      path: '/dm-setter/inbox'
      fullPath: '/app/dm-setter/inbox'
      preLoaderRoute: typeof AppAuthenticatedDmSetterInboxRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-setter/calendar': {
      id: '/app/_authenticated/dm-setter/calendar'
      path: '/dm-setter/calendar'
      fullPath: '/app/dm-setter/calendar'
      preLoaderRoute: typeof AppAuthenticatedDmSetterCalendarRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-manager/modules': {
      id: '/app/_authenticated/dm-manager/modules'
      path: '/dm-manager/modules'
      fullPath: '/app/dm-manager/modules'
      preLoaderRoute: typeof AppAuthenticatedDmManagerModulesRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dm-manager/calendar': {
      id: '/app/_authenticated/dm-manager/calendar'
      path: '/dm-manager/calendar'
      fullPath: '/app/dm-manager/calendar'
      preLoaderRoute: typeof AppAuthenticatedDmManagerCalendarRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/closer/commissions': {
      id: '/app/_authenticated/closer/commissions'
      path: '/closer/commissions'
      fullPath: '/app/closer/commissions'
      preLoaderRoute: typeof AppAuthenticatedCloserCommissionsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/closer/calendar': {
      id: '/app/_authenticated/closer/calendar'
      path: '/closer/calendar'
      fullPath: '/app/closer/calendar'
      preLoaderRoute: typeof AppAuthenticatedCloserCalendarRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/tickets': {
      id: '/app/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/app/admin/tickets'
      preLoaderRoute: typeof AppAuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/settings': {
      id: '/app/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/quizzes': {
      id: '/app/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/app/admin/quizzes'
      preLoaderRoute: typeof AppAuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/pif-payments': {
      id: '/app/_authenticated/admin/pif-payments'
      path: '/pif-payments'
      fullPath: '/app/admin/pif-payments'
      preLoaderRoute: typeof AppAuthenticatedAdminPifPaymentsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/modules': {
      id: '/app/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/app/admin/modules'
      preLoaderRoute: typeof AppAuthenticatedAdminModulesRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/manager-calendars': {
      id: '/app/_authenticated/admin/manager-calendars'
      path: '/manager-calendars'
      fullPath: '/app/admin/manager-calendars'
      preLoaderRoute: typeof AppAuthenticatedAdminManagerCalendarsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/dm-setters': {
      id: '/app/_authenticated/admin/dm-setters'
      path: '/dm-setters'
      fullPath: '/app/admin/dm-setters'
      preLoaderRoute: typeof AppAuthenticatedAdminDmSettersRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/closers': {
      id: '/app/_authenticated/admin/closers'
      path: '/closers'
      fullPath: '/app/admin/closers'
      preLoaderRoute: typeof AppAuthenticatedAdminClosersRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/bookings': {
      id: '/app/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/app/admin/bookings'
      preLoaderRoute: typeof AppAuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/b2c-commissions': {
      id: '/app/_authenticated/admin/b2c-commissions'
      path: '/b2c-commissions'
      fullPath: '/app/admin/b2c-commissions'
      preLoaderRoute: typeof AppAuthenticatedAdminB2cCommissionsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/applications': {
      id: '/app/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/app/admin/applications'
      preLoaderRoute: typeof AppAuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/admins': {
      id: '/app/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/app/admin/admins'
      preLoaderRoute: typeof AppAuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/app/_authenticated/admin/account-deletions': {
      id: '/app/_authenticated/admin/account-deletions'
      path: '/account-deletions'
      fullPath: '/app/admin/account-deletions'
      preLoaderRoute: typeof AppAuthenticatedAdminAccountDeletionsRouteImport
      parentRoute: typeof AppAuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/smartlead': {
      id: '/api/public/webhooks/smartlead'
      path: '/api/public/webhooks/smartlead'
      fullPath: '/api/public/webhooks/smartlead'
      preLoaderRoute: typeof ApiPublicWebhooksSmartleadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-pif-payments': {
      id: '/api/public/hooks/sync-pif-payments'
      path: '/api/public/hooks/sync-pif-payments'
      fullPath: '/api/public/hooks/sync-pif-payments'
      preLoaderRoute: typeof ApiPublicHooksSyncPifPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/smartlead-sync': {
      id: '/api/public/hooks/smartlead-sync'
      path: '/api/public/hooks/smartlead-sync'
      fullPath: '/api/public/hooks/smartlead-sync'
      preLoaderRoute: typeof ApiPublicHooksSmartleadSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-call-reminders': {
      id: '/api/public/hooks/send-call-reminders'
      path: '/api/public/hooks/send-call-reminders'
      fullPath: '/api/public/hooks/send-call-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendCallRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-dm-screenshots': {
      id: '/api/public/hooks/purge-dm-screenshots'
      path: '/api/public/hooks/purge-dm-screenshots'
      fullPath: '/api/public/hooks/purge-dm-screenshots'
      preLoaderRoute: typeof ApiPublicHooksPurgeDmScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mark-unbooked': {
      id: '/api/public/hooks/mark-unbooked'
      path: '/api/public/hooks/mark-unbooked'
      fullPath: '/api/public/hooks/mark-unbooked'
      preLoaderRoute: typeof ApiPublicHooksMarkUnbookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ghl-booking': {
      id: '/api/public/hooks/ghl-booking'
      path: '/api/public/hooks/ghl-booking'
      fullPath: '/api/public/hooks/ghl-booking'
      preLoaderRoute: typeof ApiPublicHooksGhlBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAuthenticatedAdminRouteRouteChildren {
  AppAuthenticatedAdminAccountDeletionsRoute: typeof AppAuthenticatedAdminAccountDeletionsRoute
  AppAuthenticatedAdminAdminsRoute: typeof AppAuthenticatedAdminAdminsRoute
  AppAuthenticatedAdminApplicationsRoute: typeof AppAuthenticatedAdminApplicationsRoute
  AppAuthenticatedAdminB2cCommissionsRoute: typeof AppAuthenticatedAdminB2cCommissionsRoute
  AppAuthenticatedAdminBookingsRoute: typeof AppAuthenticatedAdminBookingsRoute
  AppAuthenticatedAdminClosersRoute: typeof AppAuthenticatedAdminClosersRoute
  AppAuthenticatedAdminDmSettersRoute: typeof AppAuthenticatedAdminDmSettersRoute
  AppAuthenticatedAdminManagerCalendarsRoute: typeof AppAuthenticatedAdminManagerCalendarsRoute
  AppAuthenticatedAdminModulesRoute: typeof AppAuthenticatedAdminModulesRoute
  AppAuthenticatedAdminPifPaymentsRoute: typeof AppAuthenticatedAdminPifPaymentsRoute
  AppAuthenticatedAdminQuizzesRoute: typeof AppAuthenticatedAdminQuizzesRoute
  AppAuthenticatedAdminSettingsRoute: typeof AppAuthenticatedAdminSettingsRoute
  AppAuthenticatedAdminTicketsRoute: typeof AppAuthenticatedAdminTicketsRoute
  AppAuthenticatedAdminIndexRoute: typeof AppAuthenticatedAdminIndexRoute
}

const AppAuthenticatedAdminRouteRouteChildren: AppAuthenticatedAdminRouteRouteChildren =
  {
    AppAuthenticatedAdminAccountDeletionsRoute:
      AppAuthenticatedAdminAccountDeletionsRoute,
    AppAuthenticatedAdminAdminsRoute: AppAuthenticatedAdminAdminsRoute,
    AppAuthenticatedAdminApplicationsRoute:
      AppAuthenticatedAdminApplicationsRoute,
    AppAuthenticatedAdminB2cCommissionsRoute:
      AppAuthenticatedAdminB2cCommissionsRoute,
    AppAuthenticatedAdminBookingsRoute: AppAuthenticatedAdminBookingsRoute,
    AppAuthenticatedAdminClosersRoute: AppAuthenticatedAdminClosersRoute,
    AppAuthenticatedAdminDmSettersRoute: AppAuthenticatedAdminDmSettersRoute,
    AppAuthenticatedAdminManagerCalendarsRoute:
      AppAuthenticatedAdminManagerCalendarsRoute,
    AppAuthenticatedAdminModulesRoute: AppAuthenticatedAdminModulesRoute,
    AppAuthenticatedAdminPifPaymentsRoute:
      AppAuthenticatedAdminPifPaymentsRoute,
    AppAuthenticatedAdminQuizzesRoute: AppAuthenticatedAdminQuizzesRoute,
    AppAuthenticatedAdminSettingsRoute: AppAuthenticatedAdminSettingsRoute,
    AppAuthenticatedAdminTicketsRoute: AppAuthenticatedAdminTicketsRoute,
    AppAuthenticatedAdminIndexRoute: AppAuthenticatedAdminIndexRoute,
  }

const AppAuthenticatedAdminRouteRouteWithChildren =
  AppAuthenticatedAdminRouteRoute._addFileChildren(
    AppAuthenticatedAdminRouteRouteChildren,
  )

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedAdminRouteRoute: typeof AppAuthenticatedAdminRouteRouteWithChildren
  AppAuthenticatedCommissionsRoute: typeof AppAuthenticatedCommissionsRoute
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
  AppAuthenticatedSetPasswordRoute: typeof AppAuthenticatedSetPasswordRoute
  AppAuthenticatedTicketsRoute: typeof AppAuthenticatedTicketsRoute
  AppAuthenticatedCloserCalendarRoute: typeof AppAuthenticatedCloserCalendarRoute
  AppAuthenticatedCloserCommissionsRoute: typeof AppAuthenticatedCloserCommissionsRoute
  AppAuthenticatedDmManagerCalendarRoute: typeof AppAuthenticatedDmManagerCalendarRoute
  AppAuthenticatedDmManagerModulesRoute: typeof AppAuthenticatedDmManagerModulesRoute
  AppAuthenticatedDmSetterCalendarRoute: typeof AppAuthenticatedDmSetterCalendarRoute
  AppAuthenticatedDmSetterInboxRoute: typeof AppAuthenticatedDmSetterInboxRoute
  AppAuthenticatedDmSetterLogsRoute: typeof AppAuthenticatedDmSetterLogsRoute
  AppAuthenticatedTrainingModuleIdRoute: typeof AppAuthenticatedTrainingModuleIdRoute
  AppAuthenticatedCloserIndexRoute: typeof AppAuthenticatedCloserIndexRoute
  AppAuthenticatedDmManagerIndexRoute: typeof AppAuthenticatedDmManagerIndexRoute
  AppAuthenticatedDmSetterIndexRoute: typeof AppAuthenticatedDmSetterIndexRoute
  AppAuthenticatedTrainingIndexRoute: typeof AppAuthenticatedTrainingIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedAdminRouteRoute: AppAuthenticatedAdminRouteRouteWithChildren,
  AppAuthenticatedCommissionsRoute: AppAuthenticatedCommissionsRoute,
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
  AppAuthenticatedSetPasswordRoute: AppAuthenticatedSetPasswordRoute,
  AppAuthenticatedTicketsRoute: AppAuthenticatedTicketsRoute,
  AppAuthenticatedCloserCalendarRoute: AppAuthenticatedCloserCalendarRoute,
  AppAuthenticatedCloserCommissionsRoute:
    AppAuthenticatedCloserCommissionsRoute,
  AppAuthenticatedDmManagerCalendarRoute:
    AppAuthenticatedDmManagerCalendarRoute,
  AppAuthenticatedDmManagerModulesRoute: AppAuthenticatedDmManagerModulesRoute,
  AppAuthenticatedDmSetterCalendarRoute: AppAuthenticatedDmSetterCalendarRoute,
  AppAuthenticatedDmSetterInboxRoute: AppAuthenticatedDmSetterInboxRoute,
  AppAuthenticatedDmSetterLogsRoute: AppAuthenticatedDmSetterLogsRoute,
  AppAuthenticatedTrainingModuleIdRoute: AppAuthenticatedTrainingModuleIdRoute,
  AppAuthenticatedCloserIndexRoute: AppAuthenticatedCloserIndexRoute,
  AppAuthenticatedDmManagerIndexRoute: AppAuthenticatedDmManagerIndexRoute,
  AppAuthenticatedDmSetterIndexRoute: AppAuthenticatedDmSetterIndexRoute,
  AppAuthenticatedTrainingIndexRoute: AppAuthenticatedTrainingIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppAuthRoute: typeof AppAuthRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppAuthRoute: AppAuthRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  ConfirmBookingRoute: ConfirmBookingRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CallSlugRoute: CallSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicConfirmBookingRoute: ApiPublicConfirmBookingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicHooksGhlBookingRoute: ApiPublicHooksGhlBookingRoute,
  ApiPublicHooksMarkUnbookedRoute: ApiPublicHooksMarkUnbookedRoute,
  ApiPublicHooksPurgeDmScreenshotsRoute: ApiPublicHooksPurgeDmScreenshotsRoute,
  ApiPublicHooksSendCallRemindersRoute: ApiPublicHooksSendCallRemindersRoute,
  ApiPublicHooksSmartleadSyncRoute: ApiPublicHooksSmartleadSyncRoute,
  ApiPublicHooksSyncPifPaymentsRoute: ApiPublicHooksSyncPifPaymentsRoute,
  ApiPublicWebhooksSmartleadRoute: ApiPublicWebhooksSmartleadRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
